/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package SOS.resource.SOS.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class SOSFollowSetProvider {
	
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_0 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_0_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_1 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_8_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_2 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_1_0_0_0_0_0_0_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_3 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_1_0_0_0_0_1_0_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_4 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_12_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_5 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_13_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_6 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_19_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_7 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_20_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_8 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_21_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_9 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_22_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_10 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_23_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_11 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_24_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_12 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_25_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_13 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_7_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_14 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_1_0_0_0_0_0_0_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_15 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_1_0_0_1_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_16 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_10_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_17 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_2_0_0_1_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_18 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_3_0_0_1_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_19 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_20_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_20 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_5_0_0_0_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_21 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_5_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_22 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_5_0_0_4);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_23 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_5_0_0_6);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_24 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_5_0_0_7);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_25 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_5_0_0_8);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_26 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_6_0_0_0_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_27 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_6_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_28 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_7_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_29 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_8_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_30 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_8_0_0_2_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_31 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_8_0_0_3_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_32 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_8_0_0_4_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_33 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_8_0_0_5_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_34 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_8_0_0_6_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_35 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_17_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_36 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_9_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_37 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_11_0_0_0_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_38 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_9_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_39 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_16_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_40 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_18_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_41 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_28_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_42 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_9_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_43 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_9_0_0_5);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_44 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_10_0_0_1_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_45 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_10_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_46 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_11_0_0_0_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_47 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_11_0_0_0_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_48 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_11_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_49 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_12_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_50 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_13_0_0_2_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_51 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_14_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_52 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_15_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_53 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_20_0_0_1_0_0_1_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_54 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_21_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_55 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_22_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_56 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_23_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_57 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_24_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_58 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_25_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_59 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_26_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_60 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_27_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_61 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_13_0_0_1_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_62 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_13_0_0_1_0_0_1_0_0_0);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_63 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_13_0_0_2_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_64 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_18_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_65 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_18_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_66 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_21_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_67 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_21_0_0_5);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_68 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_22_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_69 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_22_0_0_5);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_70 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_23_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_71 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_23_0_0_5);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_72 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_24_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_73 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_24_0_0_5);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_74 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_25_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_75 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_25_0_0_5);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_76 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_26_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_77 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_26_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_78 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_27_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_79 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_28_0_0_1);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_80 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_28_0_0_2);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_81 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_28_0_0_3);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_82 = new SOS.resource.SOS.mopp.SOSExpectedStructuralFeature(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_28_0_0_4);
	public final static SOS.resource.SOS.ISOSExpectedElement TERMINAL_83 = new SOS.resource.SOS.mopp.SOSExpectedCsString(SOS.resource.SOS.grammar.SOSGrammarInformationProvider.SOS_28_0_0_5);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_0 = SOS.SOSPackage.eINSTANCE.getSemantics().getEStructuralFeature(SOS.SOSPackage.SEMANTICS__RULES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_1 = SOS.SOSPackage.eINSTANCE.getSemantics().getEStructuralFeature(SOS.SOSPackage.SEMANTICS__SIGNATURE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_2 = SOS.SOSPackage.eINSTANCE.getTransition().getEStructuralFeature(SOS.SOSPackage.TRANSITION__ENVIRONMENT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_3 = SOS.SOSPackage.eINSTANCE.getPremisseList().getEStructuralFeature(SOS.SOSPackage.PREMISSE_LIST__HAS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_4 = SOS.SOSPackage.eINSTANCE.getRule().getEStructuralFeature(SOS.SOSPackage.RULE__ASSUMES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_5 = SOS.SOSPackage.eINSTANCE.getConclusion().getEStructuralFeature(SOS.SOSPackage.CONCLUSION__HAS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_6 = SOS.SOSPackage.eINSTANCE.getRule().getEStructuralFeature(SOS.SOSPackage.RULE__CONCLUDES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_7 = SOS.SOSPackage.eINSTANCE.getRule().getEStructuralFeature(SOS.SOSPackage.RULE__OWNED_VARIABLES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_8 = SOS.SOSPackage.eINSTANCE.getPremisseList().getEStructuralFeature(SOS.SOSPackage.PREMISSE_LIST__NEXT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_9 = SOS.SOSPackage.eINSTANCE.getAlgebraicConditionList().getEStructuralFeature(SOS.SOSPackage.ALGEBRAIC_CONDITION_LIST__HAS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_10 = SOS.SOSPackage.eINSTANCE.getAlgebraicConditionList().getEStructuralFeature(SOS.SOSPackage.ALGEBRAIC_CONDITION_LIST__NEXT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_11 = SOS.adtmm.AdtmmPackage.eINSTANCE.getAbstractEquation().getEStructuralFeature(SOS.adtmm.AdtmmPackage.ABSTRACT_EQUATION__OWNED_LEFT_TERM);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_12 = SOS.SOSPackage.eINSTANCE.getAlgebraicCondition().getEStructuralFeature(SOS.SOSPackage.ALGEBRAIC_CONDITION__OWNED_CONDITIONS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_13 = SOS.SOSPackage.eINSTANCE.getTransition().getEStructuralFeature(SOS.SOSPackage.TRANSITION__PRE_STATE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_14 = SOS.SOSPackage.eINSTANCE.getTransition().getEStructuralFeature(SOS.SOSPackage.TRANSITION__LABEL);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_15 = SOS.SOSPackage.eINSTANCE.getTransition().getEStructuralFeature(SOS.SOSPackage.TRANSITION__POS_STATE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_16 = SOS.SOSPackage.eINSTANCE.getTypeJudment().getEStructuralFeature(SOS.SOSPackage.TYPE_JUDMENT__LEFT_HAND_SIDE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_17 = SOS.SOSPackage.eINSTANCE.getTypeJudment().getEStructuralFeature(SOS.SOSPackage.TYPE_JUDMENT__RIGHT_HAND_SIDE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_18 = SOS.adtmm.AdtmmPackage.eINSTANCE.getADT().getEStructuralFeature(SOS.adtmm.AdtmmPackage.ADT__OWNED_SORTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_19 = SOS.adtmm.AdtmmPackage.eINSTANCE.getADT().getEStructuralFeature(SOS.adtmm.AdtmmPackage.ADT__OWNED_GENERATORS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_20 = SOS.adtmm.AdtmmPackage.eINSTANCE.getADT().getEStructuralFeature(SOS.adtmm.AdtmmPackage.ADT__OWNED_OPERATIONS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_21 = SOS.adtmm.AdtmmPackage.eINSTANCE.getADT().getEStructuralFeature(SOS.adtmm.AdtmmPackage.ADT__OWNED_AXIOMS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_22 = SOS.adtmm.AdtmmPackage.eINSTANCE.getCondEquation().getEStructuralFeature(SOS.adtmm.AdtmmPackage.COND_EQUATION__OWNED_EQUATION);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_23 = SOS.adtmm.AdtmmPackage.eINSTANCE.getADT().getEStructuralFeature(SOS.adtmm.AdtmmPackage.ADT__OWNED_VARIABLES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_24 = SOS.adtmm.AdtmmPackage.eINSTANCE.getOperation().getEStructuralFeature(SOS.adtmm.AdtmmPackage.OPERATION__OPERATION_SORTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_25 = SOS.adtmm.AdtmmPackage.eINSTANCE.getOperation().getEStructuralFeature(SOS.adtmm.AdtmmPackage.OPERATION__RESULT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_26 = SOS.adtmm.AdtmmPackage.eINSTANCE.getVariable().getEStructuralFeature(SOS.adtmm.AdtmmPackage.VARIABLE__VARIABLE_SORT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_27 = SOS.adtmm.AdtmmPackage.eINSTANCE.getCondEquation().getEStructuralFeature(SOS.adtmm.AdtmmPackage.COND_EQUATION__OWNED_CONDITIONS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_28 = SOS.adtmm.AdtmmPackage.eINSTANCE.getCTerm().getEStructuralFeature(SOS.adtmm.AdtmmPackage.CTERM__ITER_TERM);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_29 = SOS.adtmm.AdtmmPackage.eINSTANCE.getCTerm().getEStructuralFeature(SOS.adtmm.AdtmmPackage.CTERM__OWNED_TERMS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_30 = SOS.adtmm.AdtmmPackage.eINSTANCE.getAbstractEquation().getEStructuralFeature(SOS.adtmm.AdtmmPackage.ABSTRACT_EQUATION__OWNED_RIGHT_TERM);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_31 = SOS.set.SetPackage.eINSTANCE.getSet().getEStructuralFeature(SOS.set.SetPackage.SET__SORT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_32 = SOS.set.SetPackage.eINSTANCE.getSetConstructor().getEStructuralFeature(SOS.set.SetPackage.SET_CONSTRUCTOR__MEMBER);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_33 = SOS.set.SetPackage.eINSTANCE.getSetConstructor().getEStructuralFeature(SOS.set.SetPackage.SET_CONSTRUCTOR__SUCH_THAT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_34 = SOS.set.SetPackage.eINSTANCE.getSetMembership().getEStructuralFeature(SOS.set.SetPackage.SET_MEMBERSHIP__LEFT_HAND_SIDE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_35 = SOS.set.SetPackage.eINSTANCE.getSetMembership().getEStructuralFeature(SOS.set.SetPackage.SET_MEMBERSHIP__RIGHT_HAND_SIDE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_36 = SOS.set.SetPackage.eINSTANCE.getSetOperator().getEStructuralFeature(SOS.set.SetPackage.SET_OPERATOR__LEFT_HAND_SIDE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_37 = SOS.set.SetPackage.eINSTANCE.getSetOperator().getEStructuralFeature(SOS.set.SetPackage.SET_OPERATOR__RIGHT_HAND_SIDE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_38 = SOS.set.SetPackage.eINSTANCE.getModelRelation().getEStructuralFeature(SOS.set.SetPackage.MODEL_RELATION__TARGET);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] EMPTY_FEATURE_ARRAY = new org.eclipse.emf.ecore.EStructuralFeature[0];
	
	public static void wire0() {
		TERMINAL_0.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_0.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_0.addFollower(TERMINAL_1, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_2.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_4, });
		TERMINAL_14.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_5, FEATURE_6, });
		TERMINAL_3.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, FEATURE_6, });
		TERMINAL_15.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_17.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_8, });
		TERMINAL_17.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_8, });
		TERMINAL_17.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_8, });
		TERMINAL_17.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_8, });
		TERMINAL_17.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_8, });
		TERMINAL_17.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_8, });
		TERMINAL_17.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_8, });
		TERMINAL_17.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_8, });
		TERMINAL_17.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, FEATURE_3, FEATURE_8, });
		TERMINAL_17.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, FEATURE_8, });
		TERMINAL_18.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_10, });
		TERMINAL_18.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_10, });
		TERMINAL_20.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_20.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_20.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_20.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_20.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_20.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_20.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_20.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_20.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_21.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_21.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_21.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_21.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_21.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_21.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_21.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_21.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_21.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_22.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_22.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_22.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_22.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_22.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_22.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_22.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_22.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_22.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_23.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_24.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_25.addFollower(TERMINAL_17, EMPTY_FEATURE_ARRAY);
		TERMINAL_25.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_26.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_26.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_26.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_26.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_26.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_26.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_26.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_26.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_26.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_27.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_27.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_27.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_27.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_27.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_27.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_27.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_27.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_27.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_13.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, });
		TERMINAL_13.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, });
		TERMINAL_13.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, });
		TERMINAL_13.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, });
		TERMINAL_13.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, });
		TERMINAL_13.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, });
		TERMINAL_13.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, });
		TERMINAL_13.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, });
		TERMINAL_13.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, });
		TERMINAL_28.addFollower(TERMINAL_17, EMPTY_FEATURE_ARRAY);
		TERMINAL_28.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_28.addFollower(TERMINAL_18, EMPTY_FEATURE_ARRAY);
		TERMINAL_28.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_1.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_34, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_29.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_29.addFollower(TERMINAL_1, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_30.addFollower(TERMINAL_35, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_18, });
		TERMINAL_31.addFollower(TERMINAL_36, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_19, });
		TERMINAL_32.addFollower(TERMINAL_36, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_20, });
		TERMINAL_33.addFollower(TERMINAL_37, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_21, });
		TERMINAL_33.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_33.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_33.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_33.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_33.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_33.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_33.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_33.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_33.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_34.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_23, });
		TERMINAL_36.addFollower(TERMINAL_38, EMPTY_FEATURE_ARRAY);
		TERMINAL_38.addFollower(TERMINAL_39, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_38.addFollower(TERMINAL_40, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_38.addFollower(TERMINAL_41, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_38.addFollower(TERMINAL_42, EMPTY_FEATURE_ARRAY);
		TERMINAL_42.addFollower(TERMINAL_39, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_25, });
		TERMINAL_42.addFollower(TERMINAL_40, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_25, });
		TERMINAL_42.addFollower(TERMINAL_41, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_25, });
		TERMINAL_43.addFollower(TERMINAL_36, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_19, });
		TERMINAL_43.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_43.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_43.addFollower(TERMINAL_34, EMPTY_FEATURE_ARRAY);
		TERMINAL_43.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_43.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_43.addFollower(TERMINAL_1, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_16.addFollower(TERMINAL_44, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_45, EMPTY_FEATURE_ARRAY);
		TERMINAL_44.addFollower(TERMINAL_39, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_26, });
		TERMINAL_44.addFollower(TERMINAL_40, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_26, });
		TERMINAL_44.addFollower(TERMINAL_41, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_26, });
		TERMINAL_45.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_45.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_45.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_45.addFollower(TERMINAL_1, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_37.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_27, });
		TERMINAL_37.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_27, });
		TERMINAL_37.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_27, });
		TERMINAL_37.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_27, });
		TERMINAL_37.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_27, });
		TERMINAL_37.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_27, });
		TERMINAL_37.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_27, });
		TERMINAL_37.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_27, });
		TERMINAL_37.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_27, });
		TERMINAL_46.addFollower(TERMINAL_47, EMPTY_FEATURE_ARRAY);
		TERMINAL_47.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, });
		TERMINAL_47.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, });
		TERMINAL_47.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, });
		TERMINAL_47.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, });
		TERMINAL_47.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, });
		TERMINAL_47.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, });
		TERMINAL_47.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, });
		TERMINAL_47.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, });
		TERMINAL_47.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, });
		TERMINAL_48.addFollower(TERMINAL_37, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_22, FEATURE_21, });
		TERMINAL_48.addFollower(TERMINAL_34, EMPTY_FEATURE_ARRAY);
		TERMINAL_48.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_48.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_48.addFollower(TERMINAL_1, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_4.addFollower(TERMINAL_49, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_59, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_60, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_61, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_61.addFollower(TERMINAL_62, EMPTY_FEATURE_ARRAY);
		TERMINAL_61.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_28, });
		TERMINAL_61.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_28, });
		TERMINAL_61.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_28, });
		TERMINAL_61.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_28, });
		TERMINAL_61.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_28, });
		TERMINAL_61.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_28, });
		TERMINAL_61.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_28, });
		TERMINAL_61.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_28, });
		TERMINAL_61.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_28, });
		TERMINAL_62.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_50.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_29, });
		TERMINAL_50.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_29, });
		TERMINAL_50.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_29, });
		TERMINAL_50.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_29, });
		TERMINAL_50.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_29, });
		TERMINAL_50.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_29, });
		TERMINAL_50.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_29, });
		TERMINAL_50.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_29, });
		TERMINAL_50.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_29, });
		TERMINAL_63.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_51.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_51.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_51.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_51.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_51.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_51.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_51.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_51.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_51.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_52.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_52.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_52.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_52.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_52.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_52.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_52.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_52.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_52.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_30, });
		TERMINAL_39.addFollower(TERMINAL_39, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_39.addFollower(TERMINAL_40, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_39.addFollower(TERMINAL_41, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_39.addFollower(TERMINAL_42, EMPTY_FEATURE_ARRAY);
		TERMINAL_39.addFollower(TERMINAL_45, EMPTY_FEATURE_ARRAY);
		TERMINAL_39.addFollower(TERMINAL_64, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_35, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_18, });
		TERMINAL_35.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_34, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_35.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_35.addFollower(TERMINAL_1, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_40.addFollower(TERMINAL_65, EMPTY_FEATURE_ARRAY);
		TERMINAL_65.addFollower(TERMINAL_39, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_31, });
		TERMINAL_65.addFollower(TERMINAL_40, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_31, });
		TERMINAL_65.addFollower(TERMINAL_41, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_31, });
		TERMINAL_64.addFollower(TERMINAL_39, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_64.addFollower(TERMINAL_40, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_64.addFollower(TERMINAL_41, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_64.addFollower(TERMINAL_42, EMPTY_FEATURE_ARRAY);
		TERMINAL_64.addFollower(TERMINAL_45, EMPTY_FEATURE_ARRAY);
		TERMINAL_64.addFollower(TERMINAL_64, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_7.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_32, });
		TERMINAL_7.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_32, });
		TERMINAL_7.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_32, });
		TERMINAL_7.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_32, });
		TERMINAL_7.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_32, });
		TERMINAL_7.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_32, });
		TERMINAL_7.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_32, });
		TERMINAL_7.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_32, });
		TERMINAL_7.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_32, });
		TERMINAL_7.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_53.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, FEATURE_33, });
		TERMINAL_53.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_33, });
		TERMINAL_53.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_33, });
		TERMINAL_53.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_33, });
		TERMINAL_53.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_33, });
		TERMINAL_53.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_33, });
		TERMINAL_53.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_33, });
		TERMINAL_53.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_33, });
		TERMINAL_53.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_33, });
		TERMINAL_53.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, FEATURE_12, FEATURE_9, FEATURE_33, });
		TERMINAL_19.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_8.addFollower(TERMINAL_66, EMPTY_FEATURE_ARRAY);
		TERMINAL_66.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_66.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_66.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_66.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_66.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_66.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_66.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_66.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_66.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_54.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_54.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_54.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_54.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_54.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_54.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_54.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_54.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_54.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_67.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_68, EMPTY_FEATURE_ARRAY);
		TERMINAL_68.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_68.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_68.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_68.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_68.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_68.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_68.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_68.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_68.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_34, });
		TERMINAL_55.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_55.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_55.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_55.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_55.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_55.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_55.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_55.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_55.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_35, });
		TERMINAL_69.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_10.addFollower(TERMINAL_70, EMPTY_FEATURE_ARRAY);
		TERMINAL_70.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_70.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_70.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_70.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_70.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_70.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_70.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_70.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_70.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_56.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_56.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_56.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_56.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_56.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_56.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_56.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_56.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_56.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_71.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_11.addFollower(TERMINAL_72, EMPTY_FEATURE_ARRAY);
		TERMINAL_72.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_72.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_72.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_72.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_72.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_72.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_72.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_72.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_72.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_57.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_57.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_57.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_57.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_57.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_57.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_57.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_57.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_57.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_73.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_12.addFollower(TERMINAL_74, EMPTY_FEATURE_ARRAY);
		TERMINAL_74.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_74.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_74.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_74.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_74.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_74.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_74.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_74.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_74.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_36, });
		TERMINAL_58.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_58.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_58.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_58.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_58.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_58.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_58.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_58.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_58.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_37, });
		TERMINAL_75.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_59.addFollower(TERMINAL_76, EMPTY_FEATURE_ARRAY);
		TERMINAL_76.addFollower(TERMINAL_77, EMPTY_FEATURE_ARRAY);
		TERMINAL_77.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_38, });
		TERMINAL_60.addFollower(TERMINAL_78, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_41.addFollower(TERMINAL_79, EMPTY_FEATURE_ARRAY);
		TERMINAL_79.addFollower(TERMINAL_80, EMPTY_FEATURE_ARRAY);
		TERMINAL_80.addFollower(TERMINAL_81, EMPTY_FEATURE_ARRAY);
		TERMINAL_81.addFollower(TERMINAL_82, EMPTY_FEATURE_ARRAY);
		TERMINAL_82.addFollower(TERMINAL_83, EMPTY_FEATURE_ARRAY);
		TERMINAL_83.addFollower(TERMINAL_39, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_83.addFollower(TERMINAL_40, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_83.addFollower(TERMINAL_41, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_24, });
		TERMINAL_83.addFollower(TERMINAL_42, EMPTY_FEATURE_ARRAY);
		TERMINAL_83.addFollower(TERMINAL_45, EMPTY_FEATURE_ARRAY);
		TERMINAL_83.addFollower(TERMINAL_64, EMPTY_FEATURE_ARRAY);
	}
	// wire the terminals
	static {
		wire0();
	}
}
