<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="formalmetamodel" nsURI="http://formalmetamodel/1.0" nsPrefix="formalmetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//AA">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ab" upperBound="-1" eType="#//B"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ba" upperBound="-1" eType="#//A"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bb" eType="#//B" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormalModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="as" upperBound="-1" eType="#//A"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cs" upperBound="-1" eType="#//C"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cs" upperBound="-1" eType="#//C"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ca" eType="#//A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AA" abstract="true"/>
</ecore:EPackage>
